using System;

namespace Falu.Payments.Reversals
{
    /// <summary>
    /// Details about a reversal for an MPESA Payment
    /// </summary>
    public class PaymentReversalMpesaDetails
    {
        /// <summary>
        /// Unique identifier for request as issued by MPESA.
        /// Only populated after request is sent to MPESA.
        /// </summary>
        public string RequestId { get; set; }

        /// <summary>
        /// Time at which the transaction was successfully completed.
        /// </summary>
        public DateTimeOffset? Completed { get; set; }

        /// <summary>
        /// Time at which the transaction failed.
        /// </summary>
        public DateTimeOffset? Failed { get; set; }

        /// <summary>
        /// Time at which the transaction was timedout.
        /// </summary>
        public DateTimeOffset? Timedout { get; set; }

        /// <summary>
        /// The message from the transaction, usually extracted from the result description.
        /// This changes over the lifecycle of the transaction to keep only the latest one.
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Unique transaction identifier generated by MPESA for this transaction.
        /// Only populated for completed transactions.
        /// </summary>
        public string ReceiptNo { get; set; }
    }
}
