using Falu.Core;
using System;

namespace Falu.Evaluations
{
    /// <summary>
    /// The statement used for an evaluation.
    /// </summary>
    public class Statement
    {
        /// <summary>
        /// Provider of the statement.
        /// </summary>
        public StatementProvider Provider { get; set; }

        /// <summary>
        /// Email found in the statement.
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// Name found in the statement
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Phone number found in the statement.
        /// </summary>
        public string Phone { get; set; }

        /// <summary>
        /// Time at which the statement was generated by the provider.
        /// </summary>
        public DateTimeOffset Generated { get; set; }

        /// <summary>
        /// Period for which the statement was generated.
        /// </summary>
        public Period Period { get; set; }
    }
}
